{% set name = "sos-python" %}
{% set version = "0.20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3dc22439df32499fb7382f95119ae06a693d160f6468f8860fb80be8e1dbc8ed

build:
  noarch: python
  number: 1
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - sos-notebook >=0.19.4
    - sos >=0.19.8

test:
  requires:
    - nose
    - pytest
    - selenium
    - python {{ python_min }}
  imports:
    - sos_python

about:
  home: https://github.com/vatlab/sos-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SoS language module for Python2 and Python3
  doc_url: https://vatlab.github.io/sos-docs/
  dev_url: https://github.com/vatlab/sos-python

extra:
  recipe-maintainers:
    - BoPeng
